# Site settings
title: 徐佩然的个人博客
email: xupeiran.sam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  徐佩然的博客
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yansu.org" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
#twitter: masonsuyan
weibo: samxupeiran
github: samxupeiran
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: https://avatars3.githubusercontent.com/u/8045289?v=3&s=400 
favicon: https://avatars3.githubusercontent.com/u/8045289?v=3&s=400

# disqus 设置
#disqus:
#  shortname: samxupeiran

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
